solved all tasks
js-tasks-ru/jsbasic-20220418-2_vlasenko pull request #3
Opened 2022-04-23 07:54 UTC by vladvlas

2022-04-23 07:55 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-23 12:28 UTC, SinimaWath requested changes

2022-04-23 12:28 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (typeof salaries[el] === 'number' && salaries[el] != false && isNaN(salaries[el]) == false && isFinite(salaries[el]) == true) {
`isNaN(salaries[el])`, `isFinite(salaries[el])` - уже возвращают boolean, поэтому нет необходимости в проверке != false, == true:
`!isNaN(..) && isFinite(...)`

2022-04-23 12:28 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
В этом сontinue и else, нет необходимости, цикл и так будет продолжаться

2022-04-24 09:26 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-24 11:49 UTC, SinimaWath approved these changes

2022-04-24 11:49 UTC, merged